### ISSUE TITLE
No Traces exported on GCP Cloud Trace

### ISSUE THREAD

**Issue by oAly** [GoogleCloudPlatform/opentelemetry-operations-cpp#5]
## Expected Behavior
Build and run the gcp exporter example and see the traces on my GCP Cloud Trace

## Actual Behavior
I was able to build and run the gcp exporter example but the traces are not exported to GCP cloud trace. The Cloud Trace v2 API doesnt seem to get any requests. I tried to run the example with the gdb debugger but I cant find any errors. Is the example done and expected to work or is it still work in progress as well? If it is done, is there a way to check if the connection is established correctly?

## Steps to Reproduce the Problem

1. build and run the example using the commands in the README

## Specifications

- Version:
- Platform: linux (fedora)

**Comment by snehilchopra** [comment]
Hi!

This is because `trace_id` and `span_id` are still not being set properly in the OpenTelemetry C++ Project.
The `SetIds` method is not yet implemented, which is supposed to be called for each span at its generation time.

**Comment by oAly** [comment]
Ya I figured. Thank you. 
Closing this issue. 
A workaround that I implemented was to set the trace and span id in the setname functions that is being called when the span is created.
